pub mod api;
pub mod cache;
pub mod logic;
pub mod models;

pub const ACCOUNT_TOKEN: &str = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGlmaWVyIjoiRlVOS0VMUVVBTE0iLCJ2ZXJzaW9uIjoidjIuMy4wIiwicmVzZXRfZGF0ZSI6IjIwMjYtMDQtMTIiLCJpYXQiOjE3NzYwOTcxNjAsInN1YiI6ImFnZW50LXRva2VuIn0.azjr4y3cBiOCjrRvrhH_lrKddryJPy1GwrzVllCrOk5V11HKilLQQkxWftv9OXSFabjOcI4vRdR0b4jqM_IcHOOewbuOib8vSdfQ6aFgJC0xH_tjKEHkHsiKl7pWPNCr4HHbp61yGcXRCxE4styNT-Ph3ZFdKx0yRJv16Kl0KBxk6q2DupIBqtsARFYNUQP9xzM5khPmj9NI7YeGuvbv8TV5AcdvMRojEIGI4OwlQoAQcTMh1B2OsN-PWrdEGGcG88LGBmnS2MKS7QXbTPliJkwWhFZymAkYgaiwQN2Fea0PRPedv5zzwDV-TtZZSmvLAyBA6DJjR5JtG2IRTH26eDV6vrpl8_imjf2EoglgAATdixefnOWzcM-V3lcbsI34zp72IVnnBkFT19HGWx-oZfDfC_-ywxSga270keOxYLzTTfJ_HDapafkepwfrE7ShaPzdrgF4QKNrAZ7JNDrYwF4i-R8TMVA-5IypmU-18WL402DYd6CIZD3QS85BHfQ0pQ9pA1FmztsU6CodPkTPIYmS7-O9u8Z-5VMoB0W4EY_X1Jo4k4mMNeTpYr0D8t3xEyRE01gOJ24ISAInfZn2i96KK1hEVw8WXwDMVhpwxb0nOsZWwJvhgH1pADyA8dCYMwpj6kZnxHARAHo7zlDyB2PwW-qs2VI7ce9pbMMmQb4";
pub const HOST_URL: &str = "https://api.spacetraders.io/v2/";

pub const CACHE_DIR: &str = "cache";
pub const AGENT_CACHE_FILE: &str = "agent_cache.json";
pub const SHIPS_CACHE_FILE: &str = "ships_cache.json";
pub const CONTRACT_CACHE_FILE: &str = "contract_cache.json";
pub const SHIPYARD_LOCATIONS_CACHE_FILE: &str = "shipyard_waypoints.json";
